2015/03/31 23:31:46 [error] [exception.CException] exception 'CException' with message 'Alias "ext.bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp\htdocs\yii\framework\YiiBase.php(196): YiiBase::import('ext.bootstrap.c...', true)
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('bootstrap')
#3 C:\xampp\htdocs\phase4\protected\views\layouts\main.php(5): CModule->__get('bootstrap')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#11 C:\xampp\htdocs\phase4\protected\views\layouts\column1.php(6): CBaseController->endContent()
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\phase4\protected\controllers\SiteController.php(32): CController->render('index')
#16 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#22 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/phase4/
---
2015/03/31 23:37:19 [error] [php] include(BController.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\phase4\protected\components\Controller.php(14): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(281): SiteController->init()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/
in C:\xampp\htdocs\phase4\protected\components\Controller.php (14)
in C:\xampp\htdocs\phase4\index.php (13)
2015/03/31 23:40:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/
---
2015/03/31 23:40:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "post".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('post')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('post')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/post')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/phase4/index.php?r=site/post
HTTP_REFERER=http://localhost/phase4/index.php?r=PostContent/graph
---
2015/03/31 23:40:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/index.php?r=site/index
---
2015/03/31 23:40:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/create".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=user/create
HTTP_REFERER=http://localhost/phase4/index.php?r=PostContent/graph
---
2015/03/31 23:40:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "post".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('post')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('post')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/post')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/phase4/index.php?r=site/post
HTTP_REFERER=http://localhost/phase4/index.php?r=user/create
---
2015/03/31 23:40:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/index.php?r=site/post
---
2015/03/31 23:40:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/index.php?r=site/index
---
2015/04/01 00:04:13 [error] [php] include(Carousel.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\phase4\themes\bootstrap\views\site\index.php(9): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#5 C:\xampp\htdocs\phase4\protected\controllers\SiteController.php(32): SiteController->render()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=site/index
in C:\xampp\htdocs\phase4\themes\bootstrap\views\site\index.php (9)
in C:\xampp\htdocs\phase4\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\phase4\index.php (13)
2015/04/01 00:25:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/index.php?r=site/post
---
2015/04/01 00:25:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "post".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('post')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('post')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/post')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/phase4/index.php?r=site/post
HTTP_REFERER=http://localhost/phase4/index.php?r=user/create
---
2015/04/01 00:25:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/create".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=user/create
HTTP_REFERER=http://localhost/phase4/index.php?r=PostContent/graph
---
2015/04/01 00:25:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/index.php?r=site/index
---
2015/04/01 00:30:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/index.php?r=site/index
---
2015/04/01 19:53:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/index.php?r=site/index
---
2015/04/01 19:53:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "post".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('post')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('post')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/post')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/phase4/index.php?r=site/post
HTTP_REFERER=http://localhost/phase4/index.php?r=PostContent/graph
---
2015/04/01 19:53:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/create".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=user/create
HTTP_REFERER=http://localhost/phase4/index.php?r=site/post
---
2015/04/03 01:59:56 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\phase4\protected\components\UserIdentity.php(26): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\phase4\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\phase4\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/phase4/index.php?r=site/login
HTTP_REFERER=http://localhost/phase4/index.php?r=site/login
---
2015/04/03 02:21:16 [error] [exception.CException] exception 'CException' with message 'Property "User.email" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('email')
#1 C:\xampp\htdocs\phase4\protected\components\UserIdentity.php(27): CActiveRecord->__get('email')
#2 C:\xampp\htdocs\phase4\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\phase4\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/phase4/index.php?r=site/login
HTTP_REFERER=http://localhost/phase4/index.php?r=site/login
---
2015/04/03 02:22:59 [error] [exception.CException] exception 'CException' with message 'Property "User.email" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('email')
#1 C:\xampp\htdocs\phase4\protected\components\UserIdentity.php(27): CActiveRecord->__get('email')
#2 C:\xampp\htdocs\phase4\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\phase4\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/phase4/index.php?r=site/login
HTTP_REFERER=http://localhost/phase4/index.php?r=site/login
---
2015/04/03 02:23:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "profile".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('profile')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('profile')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/profile')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/phase4/index.php?r=site/profile
HTTP_REFERER=http://localhost/phase4/index.php
---
2015/04/03 02:26:24 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
---
2015/04/03 02:26:48 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
---
2015/04/03 02:31:22 [error] [php] Undefined variable: model (C:\xampp\htdocs\phase4\themes\bootstrap\views\layouts\main.php:67)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): UserController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): CContentDecorator->run()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): UserController->endWidget()
#5 C:\xampp\htdocs\phase4\themes\bootstrap\views\layouts\column1.php(13): UserController->endContent()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(784): UserController->renderFile()
#9 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(102): UserController->render()
#10 unknown(0): UserController->actionUpdate()
#11 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#12 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#17 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#19 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#20 C:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#23 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=user/update&id=2
in C:\xampp\htdocs\phase4\themes\bootstrap\views\layouts\main.php (67)
in C:\xampp\htdocs\phase4\themes\bootstrap\views\layouts\column1.php (13)
in C:\xampp\htdocs\phase4\protected\controllers\UserController.php (102)
2015/04/03 02:32:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/view')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/phase4/index.php?r=site/view
HTTP_REFERER=http://localhost/phase4/index.php
---
2015/04/03 02:32:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/view')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/phase4/index.php?r=site/view
HTTP_REFERER=http://localhost/phase4/index.php
---
2015/04/03 02:32:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
HTTP_REFERER=http://localhost/phase4/index.php?r=site/view
---
2015/04/03 02:34:45 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
HTTP_REFERER=http://localhost/phase4/index.php?r=site/view
---
2015/04/03 02:38:32 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
HTTP_REFERER=http://localhost/phase4/index.php?r=site/view
---
2015/04/03 02:38:34 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
HTTP_REFERER=http://localhost/phase4/index.php?r=user/update
---
2015/04/03 02:38:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
HTTP_REFERER=http://localhost/phase4/index.php?r=user/update
---
2015/04/03 02:38:57 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
HTTP_REFERER=http://localhost/phase4/index.php?r=user/update
---
2015/04/03 02:39:20 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
HTTP_REFERER=http://localhost/phase4/index.php?r=user/update&id=2
---
2015/04/03 02:40:24 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update
HTTP_REFERER=http://localhost/phase4/index.php?r=user/update&id=2
---
2015/04/03 02:40:27 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update&2
HTTP_REFERER=http://localhost/phase4/index.php
---
2015/04/03 02:40:34 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/phase4/index.php?r=user/update&2
HTTP_REFERER=http://localhost/phase4/index.php
---
2015/04/03 02:41:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\phase4\protected\controllers\UserController.php:160
Stack trace:
#0 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(88): UserController->loadModel('3')
#1 [internal function]: UserController->actionUpdate('3')
#2 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(UserController), Array)
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UserController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('update')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/update')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/phase4/index.php?r=user/update&id=3
---
2015/04/03 03:02:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "postContent/create".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('postContent/cre...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=postContent/create
HTTP_REFERER=http://localhost/phase4/index.php?r=user/view&id=2
---
2015/04/03 03:09:37 [error] [php] Undefined variable: model (C:\xampp\htdocs\phase4\protected\views\user\index.php:10)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(133): UserController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=user/index
in C:\xampp\htdocs\phase4\protected\views\user\index.php (10)
in C:\xampp\htdocs\phase4\protected\controllers\UserController.php (133)
in C:\xampp\htdocs\phase4\index.php (13)
2015/04/03 03:10:06 [error] [php] Undefined variable: model (C:\xampp\htdocs\phase4\protected\views\user\index.php:10)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(133): UserController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=user/index
in C:\xampp\htdocs\phase4\protected\views\user\index.php (10)
in C:\xampp\htdocs\phase4\protected\controllers\UserController.php (133)
in C:\xampp\htdocs\phase4\index.php (13)
2015/04/03 03:10:35 [error] [php] Undefined variable: model (C:\xampp\htdocs\phase4\protected\views\user\index.php:10)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(133): UserController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=user/index
in C:\xampp\htdocs\phase4\protected\views\user\index.php (10)
in C:\xampp\htdocs\phase4\protected\controllers\UserController.php (133)
in C:\xampp\htdocs\phase4\index.php (13)
2015/04/03 03:10:48 [error] [php] Undefined variable: model (C:\xampp\htdocs\phase4\protected\views\user\index.php:10)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(133): UserController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=user/index
in C:\xampp\htdocs\phase4\protected\views\user\index.php (10)
in C:\xampp\htdocs\phase4\protected\controllers\UserController.php (133)
in C:\xampp\htdocs\phase4\index.php (13)
2015/04/03 03:11:09 [error] [php] Undefined variable: model (C:\xampp\htdocs\phase4\protected\views\user\index.php:10)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(133): UserController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=user/index
in C:\xampp\htdocs\phase4\protected\views\user\index.php (10)
in C:\xampp\htdocs\phase4\protected\controllers\UserController.php (133)
in C:\xampp\htdocs\phase4\index.php (13)
2015/04/03 03:11:14 [error] [php] Undefined variable: model (C:\xampp\htdocs\phase4\protected\views\user\index.php:10)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(133): UserController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=user/index
in C:\xampp\htdocs\phase4\protected\views\user\index.php (10)
in C:\xampp\htdocs\phase4\protected\controllers\UserController.php (133)
in C:\xampp\htdocs\phase4\index.php (13)
2015/04/03 03:11:20 [error] [php] Undefined variable: model (C:\xampp\htdocs\phase4\protected\views\user\index.php:10)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\xampp\htdocs\phase4\protected\controllers\UserController.php(133): UserController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\phase4\index.php(13): CWebApplication->run()
REQUEST_URI=/phase4/index.php?r=user/index
in C:\xampp\htdocs\phase4\protected\views\user\index.php (10)
in C:\xampp\htdocs\phase4\protected\controllers\UserController.php (133)
in C:\xampp\htdocs\phase4\index.php (13)
2015/04/03 06:16:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "PostContent/graph".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('PostContent/gra...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\phase4\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/phase4/index.php?r=PostContent/graph
HTTP_REFERER=http://localhost/phase4/index.php
---
